# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb92832842d57fbf7fcde5d43d40644a6ab3415fe11d8442ebf9941a3ca7b10dbad52c27a1e6afd9b0d6f93107542c4be11c4730c9d4c5aa44d2d95bd4f5bfb6

test:
  secret_key_base: 49e4166ad161f706222e2bb504420c3301383026f9c4319301c4c414208906d8940331a75269ee2055370f55c14068fac49a3cb47b24709617dc878157107f9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
